// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAowAdA9eMyMpEokkvrNvRFNhA1NvH1ikU',
    appId: '1:623678509056:web:3ae18b5620aea64bff48e5',
    messagingSenderId: '623678509056',
    projectId: 'busbuddy-5787f',
    authDomain: 'busbuddy-5787f.firebaseapp.com',
    databaseURL: 'https://busbuddy-5787f-default-rtdb.firebaseio.com',
    storageBucket: 'busbuddy-5787f.firebasestorage.app',
    measurementId: 'G-RR8RN8SXES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpWSXoOgGbY4m3QNRONQjtyUXSNLVbhtA',
    appId: '1:623678509056:android:0e1cbc8c33ad0d3aff48e5',
    messagingSenderId: '623678509056',
    projectId: 'busbuddy-5787f',
    databaseURL: 'https://busbuddy-5787f-default-rtdb.firebaseio.com',
    storageBucket: 'busbuddy-5787f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG7hGaIvZhEsntFOaYXgP3nq6bHYd5CoQ',
    appId: '1:623678509056:ios:9b80712d3c73b4e8ff48e5',
    messagingSenderId: '623678509056',
    projectId: 'busbuddy-5787f',
    databaseURL: 'https://busbuddy-5787f-default-rtdb.firebaseio.com',
    storageBucket: 'busbuddy-5787f.firebasestorage.app',
    iosClientId: '623678509056-7umbp9oj0ient3n1006uvdopv7nadgb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.busapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG7hGaIvZhEsntFOaYXgP3nq6bHYd5CoQ',
    appId: '1:623678509056:ios:9b80712d3c73b4e8ff48e5',
    messagingSenderId: '623678509056',
    projectId: 'busbuddy-5787f',
    databaseURL: 'https://busbuddy-5787f-default-rtdb.firebaseio.com',
    storageBucket: 'busbuddy-5787f.firebasestorage.app',
    iosClientId: '623678509056-7umbp9oj0ient3n1006uvdopv7nadgb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.busapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAowAdA9eMyMpEokkvrNvRFNhA1NvH1ikU',
    appId: '1:623678509056:web:1912d25bc2c224dbff48e5',
    messagingSenderId: '623678509056',
    projectId: 'busbuddy-5787f',
    authDomain: 'busbuddy-5787f.firebaseapp.com',
    databaseURL: 'https://busbuddy-5787f-default-rtdb.firebaseio.com',
    storageBucket: 'busbuddy-5787f.firebasestorage.app',
    measurementId: 'G-KL4LS80858',
  );
}
